sudo: required

services:
  - docker

script:
  - make build

deploy:
  provider: script
  script: travis/deploy_master.sh
  on:
    branch: master

  provider: script
  script: travis/deploy_release.sh
  on:
    tags: true
