sudo: required

services:
  - docker

script:
  - make build
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag imagespy:latest imagespy:$TRAVIS_TAG
  - docker push imagespy:latest
  - docker push imagespy:$TRAVIS_TAG
